server:
  port: 8443
spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      enabled: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


spring.cloud.gateway.routes:
  - id: oauth2_route
    uri: http://localhost:9999
    predicates:
      - Path=/oauth/**
  - id: group_route
    uri: http://localhost:7001
    predicates:
      - Path=/api/group/**

  - id: note_route
    uri: http://localhost:7002
    predicates:
      - Path=/api/note/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: "http://localhost:9999/.well-known/jwks.json"

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
