server:
  port: 80
spring:
  application:
    name: gateway-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info


spring.cloud.gateway.routes:
  - id: gateway
    uri: http://localhost:8443
    predicates:
      - Path=/api/**,/oauth/

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
